# permissions for end users to view freeipas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: freeipa-viewer-role
rules:
- apiGroups:
  - freeipa.redhat.com
  resources:
  - freeipas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - freeipa.redhat.com
  resources:
  - freeipas/status
  verbs:
  - get
