# https://steps.ci.openshift.org/ci-operator-reference
---
# STEPS TO TRY:
#
# - Login on ci.openshift using token, and try to pull
#   the openshift/release:golang-1.16 image; afterward
#   try to export into the local Openshift (CRC), for
#   the Openshift namespace; this should make the image
#   available when ci-operator is launched locally.

# yamllint disable rule:line-length
# yamllint disable rule:comments
# yamllint disable rule:comments-indentation

# The list of base images describe
# which images are going to be necessary outside
# of the pipeline. The key will be the alias that other
# steps use to refer to this image.
# base_images:
#     "":
#         # As is an optional string to use as the intermediate name for this reference.
#         as: ' '
#         name: ' '
#         namespace: ' '
#         tag: ' '


# BuildRootImage supports two ways to get the image that
# the pipeline will caches on. The one way is to take the reference
# from an image stream, and the other from a dockerfile.

# build_root indicate the "development" image that we need to
# build and launch any other pipeline steps.
#
# THIS IS NOT THE ARTIFACT IMAGE FOR OUR PROJECT
#
# build_root:
#   image_stream_tag:
#     name: release
#     namespace: openshift
#     tag: golang-1.16

#   image_stream_tag:
#       # As is an optional string to use as the intermediate name for this reference.
#       as: ' '
#       name: ' '
#       namespace: ' '
#       tag: ' '

#   project_image:
#     build_args:
#       - name: WORKLOAD_IMAGE
#         value: quay.io/freeipa/freeipa-openshift-container:latest
#     context_dir: '.'
#     dockerfile_path: Dockerfile

#   project_image:
#     context_dir: '.'
#     dockerfile_path: ci-operator/Dockerfile.base_root

binary_build_commands: |
  make build

build_root:
  project_image:
    context_dir: '.'
    dockerfile_path: ci-operator/Dockerfile.base_root

# build_root:
#   namespace: openshift
#   name: release
#   tag: golang-1.15
  # project_image:

  #   # BuildArgs contains build arguments that will be resolved in the Dockerfile.
  #   # See https://docs.docker.com/engine/reference/builder/#/arg for more details.
  #   # build_args:
  #   #     - # Name of the build arg.
  #   #       name: ' '
  #   #       # Value of the build arg.
  #   #       value: ' '

  #   # ContextDir is the directory in the project
  #   # from which this build should be run.
  #   context_dir: '.'

  #   # DockerfileLiteral can be used to provide an inline Dockerfile.
  #   # Mutually exclusive with DockerfilePath.
  #   # dockerfile_literal: ""

  #   # DockerfilePath is the path to a Dockerfile in the
  #   # project to run relative to the context_dir.
  #   dockerfile_path: 'Dockerfile'

  #   # Inputs is a map of tag reference name to image input changes
  #   # that will populate the build context for the Dockerfile or
  #   # alter the input image for a multi-stage build.
  #   inputs:
  #     "manager":
  #       # As is a list of multi-stage step names or image names that will
  #       # be replaced by the image reference from this step. For instance,
  #       # if the Dockerfile defines FROM nginx:latest AS base, specifying
  #       # either "nginx:latest" or "base" in this array will replace that
  #       # image with the pipeline input.
  #       as:
  #         - "builder"
  #       # Paths is a list of paths to copy out of this image and into the
  #       # context directory.
  #       paths:
  #         # DestinationDir is the directory in the destination image to copy
  #         # to.
  #         # SourcePath is a file or directory in the source image to copy from.
  #         - destination_dir: '/workspace/'
  #           source_path: 'manager'


# Images describes the images that are built
# baseImage the project as part of the release
# process. The name of each image is its "to" value
# and can be used to build only a specific image.
# images:
#   # - dockerfile_path: Dockerfile
#   #   from: base
#   #   inputs:
#   #     bin:
#   #       paths:


#   - # BuildArgs contains build arguments that will be resolved in the Dockerfile.
#     # See https://docs.docker.com/engine/reference/builder/#/arg for more details.
#     # build_args:
#     #   - # Name of the build arg.
#     #     name: ' '
#     #     # Value of the build arg.
#     #     value: ' '

#     # ContextDir is the directory in the project
#     # from which this build should be run.
#     context_dir: '.'

#     # DockerfileLiteral can be used to provide an inline Dockerfile.
#     # Mutually exclusive with DockerfilePath.
#     # dockerfile_literal: ""
#     # DockerfilePath is the path to a Dockerfile in the
#     # project to run relative to the context_dir.
#     dockerfile_path: 'Dockerfile'

#     # from: ' '

#     # Inputs is a map of tag reference name to image input changes
#     # that will populate the build context for the Dockerfile or
#     # alter the input image for a multi-stage build.
#     # inputs:
#     #   "":
#     #       # As is a list of multi-stage step names or image names that will
#     #       # be replaced by the image reference from this step. For instance,
#     #       # if the Dockerfile defines FROM nginx:latest AS base, specifying
#     #       # either "nginx:latest" or "base" in this array will replace that
#     #       # image with the pipeline input.
#     #       as:
#     #           - ""
#     #       # Paths is a list of paths to copy out of this image and into the
#     #       # context directory.
#     #       paths:
#     #           - # DestinationDir is the directory in the destination image to copy
#     #             # to.
#     #             destination_dir: ' '
#     #             # SourcePath is a file or directory in the source image to copy from.
#     #             source_path: ' '

#     to: 'freeipa-operator'

test_binary_build_commands: |
  make build-test

tests:
  - as: unit
    commands: |
      make test
    container:
      from: root

images:
  # Build the controller image by copying the results from the binary_build_commands
  - dockerfile_literal: |-
      FROM bin as builder
      FROM gcr.io/distroless/static:nonroot
      WORKDIR /
      COPY --from=builder /go/src/github.com/freeipa/freeipa-operator/bin/manager .
      USER nonroot:nonroot
      ENTRYPOINT ["/manager"]
    to: freeipa-operator

resources:
  "*":
    limits:
      cpu: "2000m"
      memory: "2000Mi"
    requests:
      cpu: "1000m"
      memory: "2000Mi"

  "crc":
    limits:
      cpu: "1000m"
      memory: "1000Mi"
    requests:
      cpu: "1000m"
      memory: "1000Mi"
