---
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#name
name: lint

# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
# yamllint disable-line rule:truthy
on: [push, pull_request]

# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobs
jobs:
  lint-files:
    name: Lint all possible files in the repository

    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest

    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idsteps
    steps:
      - uses: actions/checkout@v2

      - name: Lint Shell Script files
        run: ./devel/lint.sh  $( find . -name '*.sh' )
      - name: Lint Markdown files
        run: ./devel/lint.sh  $( find . -name '*.md' )
      - name: Lint YAML files
        run: ./devel/lint.sh  $( find . -name '*.yml' -o -name '*.yaml' )
      - name: Lint Dockerfile files
        run: |
          ./devel/lint.sh  $( find . -name 'Dockerfile' \
          -o -name 'Dockerfile.*' )
      - name: Lint go files
        run: |
          make lint
