---
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#name
name: Main

# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
# yamllint disable-line rule:truthy
on: [push, pull_request]

# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobs
jobs:
  environment:
    name: Gather information about the environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Gather environment information
        run: |
          env
          go env
          go version

      # - name: Install tools
      #   run: |
      #     export FLAG_INSTALL_VSCODE=NO
      #     export FLAG_INSTALL_CRC=NO
      #     export GOPATH="$PWD/go"
      #     [ -e "$GOPATH" ] || mkdir -p $GOPATH
      #     ./devel/install-local-tools.sh

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: local-tools
      #     path: ./go

  lint-golang:
    name: Lint golang code
    needs: [environment]

    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest

    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idsteps
    steps:
      - uses: actions/checkout@v2

      - name: Lint go files
        run: |
          [ "$GOPATH" != "" ] || export GOPATH="$( go env GOPATH )"
          go get -u golang.org/x/lint/golint
          # go install
          make lint

  lint-files:
    name: Lint all possible files in the repository but golang
    needs: [environment]

    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest

    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idsteps
    steps:
      - uses: actions/checkout@v2

      - name: Lint Shell Script files
        run: ./devel/lint.sh  $( find . -name '*.sh' )
      - name: Lint Markdown files
        run: ./devel/lint.sh  $( find . -name '*.md' )
      - name: Lint YAML files
        run: ./devel/lint.sh  $( find . -name '*.yml' -o -name '*.yaml' )
      - name: Lint Dockerfile files
        run: |
          ./devel/lint.sh  $( find . -name 'Dockerfile' \
          -o -name 'Dockerfile.*' )
